title: Mislav Jovanovic # your name (or website title) here
logo: "/images/WhatsApp Image 2021-06-24 at 00.01.16.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  21.12.1966
  mislav.jovanovic.mj@gmail.com
  Zagreb/Novska Croatia
  Unity
  C#
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
